package exporter

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/prometheus/client_golang/prometheus"
)

// recordingRegistry remembers every collector so the catalogue can be
// generated from Describe() without any data having been collected.
type recordingRegistry struct {
	*prometheus.Registry
	collectors []prometheus.Collector
}

func newRecordingRegistry() *recordingRegistry {
	return &recordingRegistry{Registry: prometheus.NewRegistry()}
}

func (r *recordingRegistry) Register(c prometheus.Collector) error {
	if err := r.Registry.Register(c); err != nil {
		return err
	}
	r.collectors = append(r.collectors, c)
	return nil
}

func (r *recordingRegistry) MustRegister(cs ...prometheus.Collector) {
	for _, c := range cs {
		if err := r.Register(c); err != nil {
			panic(err)
		}
	}
}

// descRe parses prometheus.Desc.String(). client_golang >= 1.21 adds a
// `unit` field between help and constLabels, so it is optional here.
var descRe = regexp.MustCompile(`fqName: "([^"]+)", help: ("(?:[^"\\]|\\.)*"),(?: unit: "(?:[^"\\]|\\.)*",)? constLabels: \{[^}]*\}, variableLabels: \{([^}]*)\}`)

var histograms = map[string]bool{
	"tvheadend_session_duration_seconds":              true,
	"tvheadend_exporter_poll_duration_seconds":        true,
	"tvheadend_exporter_api_request_duration_seconds": true,
}

// Catalog renders a markdown table of all registered metrics.
func Catalog(reg *recordingRegistry) string {
	type row struct{ name, typ, labels, help string }
	var rows []row
	for _, c := range reg.collectors {
		ch := make(chan *prometheus.Desc, 64)
		go func() { c.Describe(ch); close(ch) }()
		for d := range ch {
			m := descRe.FindStringSubmatch(d.String())
			if m == nil {
				continue
			}
			typ := "gauge"
			switch {
			case strings.HasSuffix(m[1], "_total"):
				typ = "counter"
			case histograms[m[1]]:
				typ = "histogram"
			}
			labels := "—"
			if m[3] != "" {
				var parts []string
				for _, l := range strings.Split(m[3], ",") {
					parts = append(parts, "`"+strings.TrimSpace(l)+"`")
				}
				labels = strings.Join(parts, ", ")
			}
			help, err := strconv.Unquote(m[2])
			if err != nil {
				help = m[2]
			}
			rows = append(rows, row{m[1], typ, labels, strings.ReplaceAll(help, "|", `\|`)})
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	var b strings.Builder
	b.WriteString("# Metrics\n\nGenerated by `tvheadend-exporter -dump-metrics`.\n\n| Metric | Type | Labels | Help |\n|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", r.name, r.typ, r.labels, r.help)
	}
	return b.String()
}
